export const menuItems = [
  {
    key: "overall",
    label: "总体框架",
    query: "MATCH (n:`一级节点`) RETURN n",
  },
  {
    key: "projectManagement",
    label: "项目管理",
    children: [
      {
        key: "laoqingshan",
        label: "老青山项目",
        query: "MATCH (n:`上能电气`) RETURN n LIMIT 25",
      },
      {
        key: "guangfuchang",
        label: "光伏村",
        query: "MATCH p=(a)-[r]->(b) WHERE a.name =~ '光伏.*' RETURN *",
      },
      // 其他子菜单项...
    ],
  },
  {
    key: "operationData",
    label: "运营数据",
    query: "MATCH p=()-[r:`24号风机`]->() RETURN p LIMIT 25",
  },
  {
    key: "supplyChain",
    label: "大部件供应链",
    query: "MATCH p=()-[r:`公司消缺项`]->() RETURN p LIMIT 25",
  },
  {
    key: "newEnergyPolicy",
    label: "新能源政策",
    query: "MATCH p=()-[r:`电力政策`]->() RETURN p LIMIT 25",
  },
  {
    key: "dataUpdate",
    label: "数据更新",
    query: "MATCH p=()-[r:`属于`]->() RETURN p LIMIT 25",
  },
  // 可以根据需要继续添加更多菜单项
];
export const labels = [
  "SVG厂家",
  "一级节点",
  "上华新能源无锡",
  "上海电气",
  "上能电气",
  "东方日升光伏",
  "东方日升新能源",
  "东方电气",
  "中清光伏",
  "中电电气光伏",
  "中节能太阳能",
  "主机厂家",
  "主齿轮箱厂家",
  "二级节点",
  "云南国际项目",
  "亿晶光电",
  "供应商",
  "偏航轴承厂家",
  "光伏支架厂家",
  "光电供应商",
  "公司消缺项",
  "具体故障风机",
  "具体风机故障信息",
  "功率预测系统厂家",
  "北京ABB电气传动系统",
  "华为技术",
  "华耀光伏科技",
  "发电机厂家",
  "变桨轴承厂家",
  "变频器厂家",
  "叶片厂家",
  "哈电风能",
  "广东易事特电源",
  "故障",
  "整体故障信息",
  "新能源政策法规",
  "易事特集团",
  "晶科能源",
  "正泰新能源",
  "气象系统厂家",
  "汇流箱厂家",
  "浙江乐叶光伏",
  "海润光伏",
  "电力价格",
  "电力市场",
  "电池组件厂家",
  "监控系统厂家",
  "箱变厂家",
  "箱变测控厂家",
  "老青山主机设备",
  "许继电气",
  "许继集团",
  "许继风电",
  "设计施工单位名",
  "轮毂厂家",
  "辐照计厂家",
  "运营单位名",
  "运营情况",
  "运营故障",
  "远景能源",
  "逆变器厂家",
  "通威光伏科技",
  "重庆海装",
  "金风科技",
  "隆基绿能",
  "项目故障",
  "项目消缺项",
  "项目节点",
  "风场大部件",
  "风机",
  "风机发电量数据",
  "风机子节点",
  "风电供应商",
  "黄河上游水电开发西宁分公司",
];
export const searchTypeToCypher = [
  {
    type: 0,
    cypher: "MATCH p=(a)-[r]->(b) WHERE a.name =~ '.*${target}.*' RETURN *",
  },
  {
    type: 1,
    cypher: "MATCH (n:Note) WHERE n.author CONTAINS $searchText RETURN n",
  },
  {
    type: 2,
    cypher: "MATCH (n:Note) WHERE n.content CONTAINS $searchText RETURN n",
  },
  {
    type: 3,
    cypher:
      "MATCH (n:Note)-[r:TAGGED]->(t:Tag) WHERE t.name CONTAINS $searchText RETURN n",
  },
];
